### ISSUE TITLE
[milestone] Convert the library to typescript

### ISSUE THREAD

**Issue by mirus-ua** [Hacker0x01/react-datepicker#4700]
# Contribution is welcome 

### Why? 

Everything started [here](https://github.com/Hacker0x01/react-datepicker/pull/4592) from the willing to merge a separate package with the corresponding type definitions into this repo. 
The idea is great, but we, as a community, can go further and migrate the entire code base into typescript. 

### Any benefits?
- only one package to install for end users
- easier to maintain
- your help to the lovely library
- ??? 
- profit

## Our steps to achieve the goal 

- [x] extend rollup and rest tools to support `.ts` and `.tsx` modules https://github.com/Hacker0x01/react-datepicker/pull/4704
- [x] migrate datepicker modules first
- [x] add a GitHub action to check types @mirus-ua https://github.com/Hacker0x01/react-datepicker/pull/4749
- [ ] update docs
- [x] migrate test cases
- [x]  use `ts-jest` @mirus-ua 
- [ ] migrate docs (optional)

### Basic rules and advice:
- start with the smallest isolated modules, like `calendar_container.jsx`
- prevent the use `any` or other loose types if you don't have strong arguments
- prevent using "[slow types](https://jsr.io/docs/about-slow-types)", give this option to the end users 
- use interfaces instead of types because the large amount of the code base is class-based
- add JSDocs where you can to improve overall DX. Everyone likes a good DX

### Steps to contribute

1. Write in the comments the name of the module that you want help to migrate 
2. Me or a maintainer will assign your name to the list to prevent doing the same job twice 
3. Migrate according to the list of advice above
4. Highly recommended to migrate test cases together with the module
5. Create a PR with a name format `[typescript-migration] calendar.jsx` etc.

- [x] calendar_icon.jsx https://github.com/Hacker0x01/react-datepicker/pull/4706
- [x] calendar_container.tsx https://github.com/Hacker0x01/react-datepicker/pull/4704
- [x] date_utils.js https://github.com/Hacker0x01/react-datepicker/pull/4707
- [x] inputTime.jsx https://github.com/Hacker0x01/react-datepicker/pull/4708
- [x] calendar.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4766
- [x] popper_component.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4740
- [x] week_number.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4714
- [x] month.jsx @mirus-ua https://github.com/Hacker0x01/react-datepicker/pull/4743
- [x] portal.jsx @Olenka-Yurchuk https://github.com/Hacker0x01/react-datepicker/pull/4722
- [x] with_floating.jsx https://github.com/Hacker0x01/react-datepicker/pull/4709
- [x] month_dropdown.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4723
- [x] year.jsx @Olenka-Yurchuk https://github.com/Hacker0x01/react-datepicker/pull/4756
- [x] month_dropdown_options.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4723
- [x] tab_loop.jsx https://github.com/Hacker0x01/react-datepicker/pull/4710
- [x] year_dropdown.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4715
- [x] day.jsx @mirus-ua https://github.com/Hacker0x01/react-datepicker/pull/4713
- [x] month_year_dropdown.jsx https://github.com/Hacker0x01/react-datepicker/pull/4724
- [x] time.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4726
- [x] year_dropdown_options.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4715
- [x] index.jsx @yuki0410-dev https://github.com/Hacker0x01/react-datepicker/pull/4766
- [x] month_year_dropdown_options.jsx https://github.com/Hacker0x01/react-datepicker/pull/4724
- [x] week.jsx https://github.com/Hacker0x01/react-datepicker/pull/4725 https://github.com/Hacker0x01/react-datepicker/pull/4725

## Breaking changes so far:
- `newDate` helper always returns a date, if the initial params were invalid, then it returns just a `new Date`  [Line](https://github.com/Hacker0x01/react-datepicker/pull/4707/files#diff-4a995d09660b3ce231c42bbd7f9073b938a2068ffb56f71f9d54683cb3c2f702R89);  [PR](https://github.com/Hacker0x01/react-datepicker/pull/4707)
- calendarIconClassname => calendarIconClassName [PR](https://github.com/Hacker0x01/react-datepicker/pull/4643#event-12569493197)

**Comment by mirus-ua** [comment]
@martijnrusschen can you pin the issue?

**Comment by martijnrusschen** [comment]
Nice progress so far!

**Comment by yuki0410-dev** [comment]
@mirus-ua ( @martijnrusschen  )
Thank you for the great attempt.
I would like to help as well, but should I declare the file to be started on this issue?

**Comment by martijnrusschen** [comment]
@yuki0410-dev Feel free to claim a file and let it know here so there's no duplicate work done.

**Comment by Olenka-Yurchuk** [comment]
I would like to take the portal jsx file in work

**Comment by yuki0410-dev** [comment]
I would like to take the week_number.jsx file in work

**Comment by mirus-ua** [comment]
Added your name to week_number.jsx

**Comment by mirus-ua** [comment]
6.6% 💪

![Знімок екрана 2024-04-23 о 17 15 33](https://github.com/Hacker0x01/react-datepicker/assets/29524085/722ca726-4178-469e-9a2e-237453fe7e85)

**Comment by yuki0410-dev** [comment]
@mirus-ua
I would like to take the month_dropdown.jsx and month_dropdown_options.jsx file in work.

**Comment by mirus-ua** [comment]
@martijnrusschen hello. Please ask reviews to look at four opened PRs if you can. It'll be much faster if we merge them because the rest of the modules depend on them

**Comment by martijnrusschen** [comment]
Yep, I'll expect them to complete this soon. Normal turnaround time is ~2-4 hours.

**Comment by yuki0410-dev** [comment]
@mirus-ua
I would like to take the month_year_dropdown.jsxand month_year_dropdown_options.jsx file in work.

**Comment by yuki0410-dev** [comment]
@mirus-ua
I would like to take the week.jsx file in work.

**Comment by Olenka-Yurchuk** [comment]
@mirus-ua I would like to take the year.jsx file in work.

**Comment by yuki0410-dev** [comment]
@mirus-ua
I would like to take the popper_component.jsx file in work.

**Comment by yuki0410-dev** [comment]
@mirus-ua
I would like to take the calendar.jsx file in work.

**Comment by yuki0410-dev** [comment]
@mirus-ua 
Modifications to index.jsx may need to be synchronized with modifications to calendar.jsx. (especially the props type)
Would it be ok if I work on it all together?

**Comment by mirus-ua** [comment]
> @mirus-ua Modifications to index.jsx may need to be synchronized with modifications to calendar.jsx. (especially the props type) Would it be ok if I work on it all together?

sure, I think you should wait a bit for the month and the year modules

**Comment by yuki0410-dev** [comment]
@mirus-ua 

> sure, I think you should wait a bit for the month and the year modules

I agree with waiting too.
We are moving forward on the calendar.jsx work, but there are some aspects that we cannot move forward on until those are completed.

**Comment by martijnrusschen** [comment]
apologies, I'm on vacation this week and don't have the ability to review
or merge anything until Friday.

**Comment by mirus-ua** [comment]
@yuki0410-dev almost everything was merged, so you can start with the final part

**Comment by martijnrusschen** [comment]
what's left?

**Comment by yuki0410-dev** [comment]
@mirus-ua (@martijnrusschen )
I would like to take the week_picker_test.test.js file in work. and fix some types.

**Comment by mirus-ua** [comment]
> what's left?

The core features are done.But I think better to migrate some amount of tests just to double check that all types are OK

**Comment by yuki0410-dev** [comment]
@mirus-ua 
I noticed during my experimentation with #4810 that type errors in the test file do not seem to result in errors in CI.
Is it my understanding that this is due to the fact that I am now using babel-jest to run tests with type information ignored, and that when I change to ts-jest later on, I will get CI errors?

**Comment by mirus-ua** [comment]
> @mirus-ua I noticed during my experimentation with #4810 that type errors in the test file do not seem to result in errors in CI. Is it my understanding that this is due to the fact that I am now using babel-jest to run tests with type information ignored, and that when I change to ts-jest later on, I will get CI errors?

everything is correct

**Comment by ryantanrk** [comment]
hi, is anyone working on these files? i would like to take 1 of them:

calendar_test.test.js
datepicker_test.test.js
month_test.test.js

**Comment by martijnrusschen** [comment]
@ryantanrk go for it :)

**Comment by ryantanrk** [comment]
i'll take month_test.test.js then if no one is working on it 👍

**Comment by yuki0410-dev** [comment]
@martijnrusschen @ryantanrk @mirus-ua 
Converted `calendar_test.test.js` and `datepicker_test.test.js`.

**Comment by Myroslav-mint** [comment]
What test modules are left?

**Comment by mirus-ua** [comment]
What test modules are left?

**Comment by yuki0410-dev** [comment]
@mirus-ua 
#4855 is merged, TS conversion of all test modules is complete.

**Comment by martijnrusschen** [comment]
Once #4855 is merged, I'll issue a major version upgrade. Are there any type/test changes we want to make once we're fully migrated to TS?

**Comment by martijnrusschen** [comment]
The issue description says: after all, use ts-jest

**Comment by mirus-ua** [comment]
Migrate to ts-jest and then go with the major

**Comment by martijnrusschen** [comment]
Sounds good. On 2 Jun 2024, at 16:36, Mirus ***@***.***> wrote:﻿
Migrate to ts-jest and then go with the major

**Comment by mirus-ua** [comment]
OK. I'll do then

**Comment by mirus-ua** [comment]
It looks like I underestimated the amount of work. Almost all tests have types issues, so I don't think that I can do it relatively fast alone

**Comment by martijnrusschen** [comment]
Is this something that could be split up somehow?

**Comment by mirus-ua** [comment]
> Is this something that could be split up somehow?

I can push the branch with basic config, and then we can use it as PRs target for this activity

**Comment by martijnrusschen** [comment]
sounds good

**Comment by mirus-ua** [comment]
I'll do today

**Comment by yuki0410-dev** [comment]
@mirus-ua 
Just a thought, but if we assign the tests to ts-jest one file at a time in the transform section, can we migrate from babel-jest to ts-jest without causing errors in CI?

**Comment by mirus-ua** [comment]
> @mirus-ua Just a thought, but if we assign the tests to ts-jest one file at a time in the transform section, can we migrate from babel-jest to ts-jest without causing errors in CI?

Do you mean [here](https://github.com/Hacker0x01/react-datepicker/pull/4870/files#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R16) explicitly add files that we migrated? It could work even if it'll be tedious

**Comment by yuki0410-dev** [comment]
@mirus-ua 
That's right.
I am trying it now in #4871 and have a base. I am going to try one file now.

**Comment by yuki0410-dev** [comment]
@mirus-ua @martijnrusschen 
It looked like we could migrate babl-jest to ts-jest while merging into the Master branch, so we created PR #4871.

**Comment by martijnrusschen** [comment]
Are we safe to cut a major release now we've converted the last tests?

**Comment by mirus-ua** [comment]
> Are we safe to cut a major release now we've converted the last tests?

I think so. We've done everything possible to integrate types safely into the existing code base and save the future feature development from type degradation

**Comment by martijnrusschen** [comment]
Cool, for the release notes, we should capture the breaking changes.

**Comment by martijnrusschen** [comment]
Here's the changelog: https://github.com/Hacker0x01/react-datepicker/releases/tag/v7.0.0

**Comment by mirus-ua** [comment]
That was a good teamwork. Thanks all.

I think the issue should be open because we have some work with docs to do

**Comment by bsal649** [comment]
I only had one custom component interfacing with ReactDatePicker but I encountered a lot of breaking changes that weren't listed in the release.

1. ReactDatePicker name changed to DatePicker.
2. ReactDatePickerProps name changed to DatePickerProps.

I had an interface as below:
```typescript
interface DateInputProps extends Partial<ReactDatePickerProps> {
  style?: React.CSSProperties;
}
```
With an onChange with below def:
```typescript
function handleChange(date: Date | null)
```

3. I had to change the interface to a custom type.
4. I had to make onChange and onSelect optional in the custom type.
5. I had to explicitly set selectsRange and selectsMultiple to undefined in order to get default behaviour.
6. I had to pass the excludesScrollbar prop in all the usages of my custom component.
7. I assume that @types/react-datepicker needs to be uninstalled but not sure about this.

In the end my interface looks like this:
```typescript
type CustomDatePickerProps = Omit<
  DatePickerProps,
  'onChange' | 'onSelect' | 'selectsRange' | 'selectsMultiple'
> & {
  onChange?: (
    date: Date | null,
    event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>,
  ) => void;
  onSelect?: (
    date: Date | null,
    event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>,
  ) => void;
  excludeScrollbar?: boolean;
  selectsRange?: boolean;
  selectsMultiple?: boolean;
};

type DateInputProps = CustomDatePickerProps & {
  style?: React.CSSProperties;
};
```

And my handleChange like this:
```typescript
function handleChange(
    date: Date | null,
    event?:
      | React.MouseEvent<HTMLElement>
      | React.KeyboardEvent<HTMLElement>
      | undefined,
  )
```

**Comment by yuki0410-dev** [comment]
@bsal649 ( @mirus-ua @martijnrusschen )
Thank you for the quick introduction.

I will answer as far as I am aware.

> 1. ReactDatePicker name changed to DatePicker.

I think you forgot to put this in the "breaking changes" section.

> 2. ReactDatePickerProps name changed to DatePickerProps.

> 3. The interface needed to be changed to a custom type.

I think this is "breaking changes" because this is a change from @types/react-datepicker, which is originally managed by someone outside this Repository member.

> 6. I had to pass the excludesScrollbar prop in all the usages of my custom component.

I could not find that Props in this current Repository.

> 7. I assume that @types/react-datepicker needs to be uninstalled but not sure about this.

It must be uninstalled.

**Comment by bsal649** [comment]
@yuki0410-dev Thanks for the explanation, and fair enough.

Maybe it'd be worth putting a note in the release that people who were using @types/react-datepicker might have a lot more breaking changes.

**Comment by martijnrusschen** [comment]
@yuki0410-dev For "ReactDatePicker name changed to DatePicker.", that doesn't seem like an intended change and will be causing everyone to make changes. Can we reduce the breaking changes by reverting to the original name? I don't see a need to force change that here. Thoughts? Same counts for "ReactDatePickerProps name changed to DatePickerProps."

**Comment by mirus-ua** [comment]
> @yuki0410-dev For "ReactDatePicker name changed to DatePicker.", that doesn't seem like an intended change and will be causing everyone to make changes. Can we reduce the breaking changes by reverting to the original name? I don't see a need to force change that here. Thoughts? Same counts for "ReactDatePickerProps name changed to DatePickerProps."

The right way, IMO, is to add these in the list of the breaking changes rather then violating semver rules

**Comment by martijnrusschen** [comment]
That would be the alternative, but it forces everyone to update their code for just a name change.

**Comment by yuki0410-dev** [comment]
@martijnrusschen @mirus-ua 
My question is, since DatePicker is export defaulted, can't we name it freely on the import side?
I don't think any modifications have occurred due to the renaming of the DatePicker class, at least in doc-site.
